export const CONFIRM_MODAL = 'CONFIRM_MODAL';
export const UPDATE_NAME_MODAL = 'UPDATE_NAME_MODAL';

export const PRODUCTS_MODAL = 'PRODUCTS_MODAL';

export const ATTRIBUTE_IN_GROUP_MODAL = 'ATTRIBUTE_IN_GROUP_MODAL';
export const OPTION_IN_GROUP_MODAL = 'OPTION_IN_GROUP_MODAL';
export const ADD_ACCESSORY_TO_RUBRIC_MODAL = 'ADD_ACCESSORY_TO_RUBRIC_MODAL';
export const ADD_PRODUCT_TO_CONTRACTOR_MODAL = 'ADD_PRODUCT_TO_CONTRACTOR_MODAL';

export const ADD_ATTRIBUTES_GROUP_TO_RUBRIC_MODAL = 'ADD_ATTRIBUTES_GROUP_TO_RUBRIC_MODAL';
export const ADD_PRODUCT_TO_RUBRIC_MODAL = 'ADD_PRODUCT_TO_RUBRIC_MODAL';
export const CREATE_NEW_PRODUCT_MODAL = 'CREATE_NEW_PRODUCT_MODAL';

export const CREATE_CONTRACTOR_MODAL = 'CREATE_CONTRACTOR_MODAL';
export const CREATE_RUBRIC_MODAL = 'CREATE_RUBRIC_MODAL';
export const CREATE_ACCESSORY_MODAL = 'CREATE_ACCESSORY_MODAL';
