version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=winepoint-db
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mongo
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      NODE_ENV: development
      PUBLIC_URL: app
      REACT_APP_API_URL: http://localhost/api
    stdin_open: true
    depends_on:
      - api
