version: '3'

services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=winenot-db
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - /usr/src/app/node_modules
    links:
      - db
