version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=winepoint-db
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - api
      - app
      - site
  api:
    container_name: api
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      - mongo
  app:
    container_name: app
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      NODE_ENV: development
      PUBLIC_URL: app
      PORT: 3001
    stdin_open: true
    depends_on:
      - api
  site:
    container_name: site
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./site
    volumes:
      - /site/node_modules
      - ./site:/site
    depends_on:
      - api

