version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=winepoint-db
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: ./api
    volumes:
      - ./api/assets:/app/assets
    depends_on:
      - mongo
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: ./app
    stdin_open: true
    depends_on:
      - api
  site:
    container_name: site
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: client
    depends_on:
      - api
