version: '3'

services:
  app:
    container_name: app
    restart: always
    build: .
    links:
      - mongo
    environment:
      NODE_ENV: development
    volumes:
      - ./packages:/usr/src/app/packages
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
