version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    env_file:
      - .env
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./dhparam:/etc/nginx/dhparam
    - ./certbot/conf/:/etc/nginx/ssl/
    - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - app
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email slava.kirshman@icloud.com --agree-tos --no-eff-email -d winepointdev.ru -d www.winepointdev.ru
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - nginx
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./api
    volumes:
      - ./api/assets:/app/assets
    env_file:
      - .env
    depends_on:
      - mongo
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./app
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - api
