version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    env_file:
      - .env
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./api
    volumes:
      - ./api/assets:/app/assets
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - mongo
  site:
    container_name: site
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: client
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - api
