version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./api
    volumes:
      - ./api/assets:/app/assets
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SESS_NAME
      - SESS_TTL
      - ADMIN_NAME
      - ADMIN_EMAIL
      - ADMIN_PHONE
      - ADMIN_PASSWORD
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.stage
      context: ./app
    stdin_open: true
    depends_on:
      - api
