version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db
    env_file:
      - .env.testing
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: ./nginx
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: ./api
    volumes:
      - ./api/assets:/api/assets
    depends_on:
      - mongo
    env_file:
      - .env.testing
  site:
    container_name: site
    restart: always
    build:
      dockerfile: Dockerfile.testing
      context: client
    depends_on:
      - api
    env_file:
      - .env.testing
