version: '3'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - mongo
    environment:
      NODE_ENV: development
      SKIP_PREFLIGHT_CHECK: "true"
      CI: "true"
    volumes:
      - ./packages:/usr/src/app/packages
    stdin_open: true
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - 80:80
