name: Deploy to the develop

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd www && git pull && docker-compose -f docker-compose.stage.yml up -d && yarn install && yarn build
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          privateKey: ${{ secrets.DEV_PRIVATE_KEY}}

