name: Build, Test, Deploy to the develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  sshAccess:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
          script: cd site && ls -a
#  apiTest:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Development
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - run: yarn install:api
#      - run: yarn test:api
#
#  appTest:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Development
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#
#    - run: yarn
#    - run: yarn install:app
#    - run: yarn up:testing
#    - run: yarn test:app
