# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test, Deploy to the develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Development
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

#    - name: Install root dependencies
#      run: yarn
#
#    - name: Install api dependencies
#      run: cd api && npm install
#
#    - name: Install app dependencies
#      run: cd app && npm install
    - run: yarn up:serve
    - run: yarn test
