name: Build and Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Build and test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: docker-compose -f docker-compose.dev.yml up -d
      - run: yarn install
#      - run: yarn seed-test-db
      - run: yarn build-and-test
        env:
          CI: true
          DEV_ENV: true
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_TEST_HOST: ${{ secrets.MONGO_TEST_HOST }}
          MONGO_TEST_USER_NAME: ${{ secrets.MONGO_TEST_USER_NAME }}
          MONGO_TEST_USER_PWD: ${{ secrets.MONGO_TEST_USER_PWD }}
          MONGO_TEST_PORT: ${{ secrets.MONGO_TEST_PORT }}
          MONGO_DB_RS: ${{ secrets.MONGO_DB_RS }}
          NEXTAUTH_KEY: ${{ secrets.NEXTAUTH_KEY }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_SIGNING_PRIVATE_KEY: ${{ secrets.JWT_SIGNING_PRIVATE_KEY }}
          OBJECT_STORAGE_KEY_ID: ${{ secrets.OBJECT_STORAGE_KEY_ID }}
          OBJECT_STORAGE_KEY: ${{ secrets.OBJECT_STORAGE_KEY }}
          OBJECT_STORAGE_BUCKET_NAME: ${{ secrets.OBJECT_STORAGE_BUCKET_NAME }}
          OBJECT_STORAGE_DOMAIN: ${{ secrets.OBJECT_STORAGE_DOMAIN }}
          OBJECT_STORAGE_IMAGE_FALLBACK: ${{ secrets.OBJECT_STORAGE_IMAGE_FALLBACK }}
          OBJECT_STORAGE_PRODUCT_IMAGE_FALLBACK: ${{ secrets.OBJECT_STORAGE_PRODUCT_IMAGE_FALLBACK }}
          NEXT_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_GOOGLE_MAPS_API_KEY }}
          DEFAULT_CITY: ${{ secrets.DEFAULT_CITY }}
          DEFAULT_LOCALE: ${{ secrets.DEFAULT_LOCALE }}
          DEFAULT_DOMAIN: ${{ secrets.DEFAULT_DOMAIN }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALG_INDEX_PRODUCTS: ${{ secrets.ALG_INDEX_PRODUCTS }}
          ALG_INDEX_SHOP_PRODUCTS: ${{ secrets.ALG_INDEX_SHOP_PRODUCTS }}

