name: Build and Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  apiTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Development
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: npx lerna run --ignore @yagu/client --ignore @yagu/api build
      - run: yarn test:api
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

  clientTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Development
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: docker-compose -f docker-compose.dev.yml up -d
      - run: yarn install
      - run: npx lerna run --ignore @yagu/client build
      - run: npx lerna run --scope @yagu/client build:testing
      - name: Start the app and run Cypress tests
        run: npx lerna run --parallel start:testing & yarn test:client
        env:
          NODE_ENV: development
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
