name: Build and Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Development
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn up:testing
      - run: yarn install:api
      - run: yarn install:client
      - run: yarn build:api
      - run: yarn build:client
      - run: yarn start:api
      - run: yarn start:client
      - run: yarn test:api
      - run: yarn test:client

#  apiTest:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Development
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - run: yarn install:api
#      - run: yarn test:api
#
#  clientTest:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Development
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - run: yarn install:client
#      - run: yarn up:testing
#      - run: yarn test:client
