name: Build and Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  clientTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Development
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: docker-compose -f docker-compose.dev.yml up -d
      - run: yarn install
      - name: Build app
        run: yarn build
        env:
          ADMIN_NAME: ${{ secrets.NEXT_DEV_ADMIN_NAME }}
          ADMIN_LAST_NAME: ${{ secrets.NEXT_DEV_ADMIN_LAST_NAME }}
          ADMIN_SECOND_NAME: ${{ secrets.NEXT_DEV_ADMIN_SECOND_NAME }}
          ADMIN_EMAIL: ${{ secrets.NEXT_DEV_ADMIN_EMAIL }}
          ADMIN_PHONE: ${{ secrets.NEXT_DEV_ADMIN_PHONE }}
          ADMIN_PASSWORD: ${{ secrets.NEXT_DEV_ADMIN_PASSWORD }}
          MONGO_URL: ${{ secrets.NEXT_DEV_MONGO_URL }}
          MONGO_DB_NAME: ${{ secrets.NEXT_DEV_MONGO_DB_NAME }}
          SITE: ${{ secrets.NEXT_TEST_SITE }}
          NEXTAUTH_URL: ${{ secrets.NEXT_TEST_NEXTAUTH_URL }}
          TEST_DATA_KEY: ${{ secrets.NEXT_DEV_TEST_DATA_KEY }}
          INITIAL_DATA_KEY: ${{ secrets.NEXT_DEV_INITIAL_DATA_KEY }}
          OBJECT_STORAGE_KEY_ID: ${{ secrets.OBJECT_STORAGE_KEY_ID }}
          OBJECT_STORAGE_KEY: ${{ secrets.OBJECT_STORAGE_KEY }}
          OBJECT_STORAGE_BUCKET_NAME: ${{ secrets.OBJECT_STORAGE_BUCKET_NAME }}
          OBJECT_STORAGE_DOMAIN: ${{ secrets.OBJECT_STORAGE_DOMAIN }}
          OBJECT_STORAGE_IMAGE_FALLBACK: ${{ secrets.NEXT_DEV_AWS_IMAGE_FALLBACK }}
          OBJECT_STORAGE_PRODUCT_IMAGE_FALLBACK: ${{ secrets.NEXT_DEV_AWS_PRODUCT_IMAGE_FALLBACK }}
          NEXT_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_DEV_GOOGLE_MAPS_API_KEY }}
      - name: Start the app and run Cypress tests
        run: yarn start & yarn test
        env:
          ADMIN_NAME: ${{ secrets.NEXT_DEV_ADMIN_NAME }}
          ADMIN_LAST_NAME: ${{ secrets.NEXT_DEV_ADMIN_LAST_NAME }}
          ADMIN_SECOND_NAME: ${{ secrets.NEXT_DEV_ADMIN_SECOND_NAME }}
          ADMIN_EMAIL: ${{ secrets.NEXT_DEV_ADMIN_EMAIL }}
          ADMIN_PHONE: ${{ secrets.NEXT_DEV_ADMIN_PHONE }}
          ADMIN_PASSWORD: ${{ secrets.NEXT_DEV_ADMIN_PASSWORD }}
          MONGO_URL: ${{ secrets.NEXT_DEV_MONGO_URL }}
          MONGO_DB_NAME: ${{ secrets.NEXT_DEV_MONGO_DB_NAME }}
          SITE: ${{ secrets.NEXT_TEST_SITE }}
          NEXTAUTH_URL: ${{ secrets.NEXT_TEST_NEXTAUTH_URL }}
          TEST_DATA_KEY: ${{ secrets.NEXT_DEV_TEST_DATA_KEY }}
          INITIAL_DATA_KEY: ${{ secrets.NEXT_DEV_INITIAL_DATA_KEY }}
          OBJECT_STORAGE_KEY_ID: ${{ secrets.OBJECT_STORAGE_KEY_ID }}
          OBJECT_STORAGE_KEY: ${{ secrets.OBJECT_STORAGE_KEY }}
          OBJECT_STORAGE_BUCKET_NAME: ${{ secrets.OBJECT_STORAGE_BUCKET_NAME }}
          OBJECT_STORAGE_DOMAIN: ${{ secrets.OBJECT_STORAGE_DOMAIN }}
          OBJECT_STORAGE_IMAGE_FALLBACK: ${{ secrets.NEXT_DEV_AWS_IMAGE_FALLBACK }}
          OBJECT_STORAGE_PRODUCT_IMAGE_FALLBACK: ${{ secrets.NEXT_DEV_AWS_PRODUCT_IMAGE_FALLBACK }}
          NEXT_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_DEV_GOOGLE_MAPS_API_KEY }}
