name: Deploy to the stage

on:
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd www/stage && git pull && yarn install && yarn build && pm2 reload stage
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          privateKey: ${{ secrets.PROD_PRIVATE_KEY }}
